/// Flutter icons WeatherIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData sun = const IconData(0xf100, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xf101, fontFamily: _kFontFam);
  static const IconData rain = const IconData(0xf102, fontFamily: _kFontFam);
}
